global:
  scrape_interval: 15s  # Увеличим интервал для стабильности
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187', 'postgres-exporter-dns:9187']  # Оба варианта имени
        labels:
          service: 'postgres-exporter'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100', 'node-exporter-dns:9100']  # Оба варианта имени
        labels:
          service: 'node-exporter'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']